/*
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.knetikcloud.api;

import com.knetikcloud.client.ApiException;
import com.knetikcloud.model.ActivityOccurrenceCreationFailure;
import com.knetikcloud.model.ActivityOccurrenceJoinResult;
import com.knetikcloud.model.ActivityOccurrenceResource;
import com.knetikcloud.model.ActivityOccurrenceResults;
import com.knetikcloud.model.ActivityOccurrenceResultsResource;
import com.knetikcloud.model.ActivityOccurrenceSettingsResource;
import com.knetikcloud.model.ActivityResource;
import com.knetikcloud.model.ActivityUserResource;
import com.knetikcloud.model.CreateActivityOccurrenceRequest;
import com.knetikcloud.model.IntWrapper;
import com.knetikcloud.model.PageResourceActivityOccurrenceResource;
import com.knetikcloud.model.PageResourceBareActivityResource;
import com.knetikcloud.model.PageResourceTemplateResource;
import com.knetikcloud.model.Result;
import com.knetikcloud.model.TemplateResource;
import com.knetikcloud.model.ValueWrapperstring;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ActivitiesApi
 */
@Ignore
public class ActivitiesApiTest {

    private final ActivitiesApi api = new ActivitiesApi();

    
    /**
     * Add a user to an occurrence
     *
     * If called with no body, defaults to the user making the call.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addUserTest() throws ApiException {
        Long activityOccurrenceId = null;
        Boolean test = null;
        Boolean bypassRestrictions = null;
        IntWrapper userId = null;
        ActivityOccurrenceResource response = api.addUser(activityOccurrenceId, test, bypassRestrictions, userId);

        // TODO: test validations
    }
    
    /**
     * Create an activity
     *
     * &lt;b&gt;Permissions Needed:&lt;/b&gt; ACTIVITIES_ADMIN
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createActivityTest() throws ApiException {
        ActivityResource activityResource = null;
        ActivityResource response = api.createActivity(activityResource);

        // TODO: test validations
    }
    
    /**
     * Create a new activity occurrence. Ex: start a game
     *
     * Has to enforce extra rules if not used as an admin. &lt;br&gt;&lt;br&gt;&lt;b&gt;Permissions Needed:&lt;/b&gt; ACTIVITIES_USER or ACTIVITIES_ADMIN
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createActivityOccurrenceTest() throws ApiException {
        Boolean test = null;
        CreateActivityOccurrenceRequest activityOccurrenceResource = null;
        ActivityOccurrenceResource response = api.createActivityOccurrence(test, activityOccurrenceResource);

        // TODO: test validations
    }
    
    /**
     * Create a activity template
     *
     * Activity Templates define a type of activity and the properties they have. &lt;br&gt;&lt;br&gt;&lt;b&gt;Permissions Needed:&lt;/b&gt; TEMPLATE_ADMIN
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createActivityTemplateTest() throws ApiException {
        TemplateResource activityTemplateResource = null;
        TemplateResource response = api.createActivityTemplate(activityTemplateResource);

        // TODO: test validations
    }
    
    /**
     * Delete an activity
     *
     * &lt;b&gt;Permissions Needed:&lt;/b&gt; ACTIVITIES_ADMIN
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteActivityTest() throws ApiException {
        Long id = null;
        api.deleteActivity(id);

        // TODO: test validations
    }
    
    /**
     * Delete a activity template
     *
     * If cascade &#x3D; &#39;detach&#39;, it will force delete the template even if it&#39;s attached to other objects. &lt;br&gt;&lt;br&gt;&lt;b&gt;Permissions Needed:&lt;/b&gt; TEMPLATE_ADMIN
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteActivityTemplateTest() throws ApiException {
        String id = null;
        String cascade = null;
        api.deleteActivityTemplate(id, cascade);

        // TODO: test validations
    }
    
    /**
     * List activity definitions
     *
     * &lt;b&gt;Permissions Needed:&lt;/b&gt; ANY
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getActivitiesTest() throws ApiException {
        Boolean filterTemplate = null;
        String filterName = null;
        String filterId = null;
        Integer size = null;
        Integer page = null;
        String order = null;
        PageResourceBareActivityResource response = api.getActivities(filterTemplate, filterName, filterId, size, page, order);

        // TODO: test validations
    }
    
    /**
     * Get a single activity
     *
     * &lt;b&gt;Permissions Needed:&lt;/b&gt; ANY
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getActivityTest() throws ApiException {
        Long id = null;
        ActivityResource response = api.getActivity(id);

        // TODO: test validations
    }
    
    /**
     * Load a single activity occurrence details
     *
     * &lt;b&gt;Permissions Needed:&lt;/b&gt; ACTIVITIES_ADMIN
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getActivityOccurrenceDetailsTest() throws ApiException {
        Long activityOccurrenceId = null;
        ActivityOccurrenceResource response = api.getActivityOccurrenceDetails(activityOccurrenceId);

        // TODO: test validations
    }
    
    /**
     * Get a single activity template
     *
     * &lt;b&gt;Permissions Needed:&lt;/b&gt; TEMPLATE_ADMIN or ACTIVITIES_ADMIN
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getActivityTemplateTest() throws ApiException {
        String id = null;
        TemplateResource response = api.getActivityTemplate(id);

        // TODO: test validations
    }
    
    /**
     * List and search activity templates
     *
     * &lt;b&gt;Permissions Needed:&lt;/b&gt; TEMPLATE_ADMIN or ACTIVITIES_ADMIN
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getActivityTemplatesTest() throws ApiException {
        Integer size = null;
        Integer page = null;
        String order = null;
        PageResourceTemplateResource response = api.getActivityTemplates(size, page, order);

        // TODO: test validations
    }
    
    /**
     * List activity occurrences
     *
     * &lt;b&gt;Permissions Needed:&lt;/b&gt; ACTIVITIES_ADMIN
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listActivityOccurrencesTest() throws ApiException {
        String filterActivity = null;
        String filterStatus = null;
        Integer filterEvent = null;
        Integer filterChallenge = null;
        Integer size = null;
        Integer page = null;
        String order = null;
        PageResourceActivityOccurrenceResource response = api.listActivityOccurrences(filterActivity, filterStatus, filterEvent, filterChallenge, size, page, order);

        // TODO: test validations
    }
    
    /**
     * Remove a user from an occurrence
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void removeUserTest() throws ApiException {
        Long activityOccurrenceId = null;
        String userId = null;
        Boolean ban = null;
        Boolean bypassRestrictions = null;
        api.removeUser(activityOccurrenceId, userId, ban, bypassRestrictions);

        // TODO: test validations
    }
    
    /**
     * Sets the status of an activity occurrence to FINISHED and logs metrics
     *
     * In addition to user permissions requirements there is security based on the core_settings.results_trust setting.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void setActivityOccurrenceResultsTest() throws ApiException {
        Long activityOccurrenceId = null;
        ActivityOccurrenceResultsResource activityOccurrenceResults = null;
        ActivityOccurrenceResults response = api.setActivityOccurrenceResults(activityOccurrenceId, activityOccurrenceResults);

        // TODO: test validations
    }
    
    /**
     * Sets the settings of an activity occurrence
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void setActivityOccurrenceSettingsTest() throws ApiException {
        Long activityOccurrenceId = null;
        ActivityOccurrenceSettingsResource settings = null;
        ActivityOccurrenceResource response = api.setActivityOccurrenceSettings(activityOccurrenceId, settings);

        // TODO: test validations
    }
    
    /**
     * Set a user&#39;s status within an occurrence
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void setUserStatusTest() throws ApiException {
        Long activityOccurrenceId = null;
        String userId = null;
        String status = null;
        ActivityUserResource response = api.setUserStatus(activityOccurrenceId, userId, status);

        // TODO: test validations
    }
    
    /**
     * Update an activity
     *
     * &lt;b&gt;Permissions Needed:&lt;/b&gt; ACTIVITIES_ADMIN
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateActivityTest() throws ApiException {
        Long id = null;
        ActivityResource activityResource = null;
        ActivityResource response = api.updateActivity(id, activityResource);

        // TODO: test validations
    }
    
    /**
     * Update the status of an activity occurrence
     *
     * If setting to &#39;FINISHED&#39; reward will be run based on current metrics that have been recorded already. Alternatively, see results endpoint to finish and record all metrics at once. Can be called by non-host participants if non_host_status_control is true
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateActivityOccurrenceStatusTest() throws ApiException {
        Long activityOccurrenceId = null;
        ValueWrapperstring activityOccurrenceStatus = null;
        api.updateActivityOccurrenceStatus(activityOccurrenceId, activityOccurrenceStatus);

        // TODO: test validations
    }
    
    /**
     * Update an activity template
     *
     * &lt;b&gt;Permissions Needed:&lt;/b&gt; TEMPLATE_ADMIN
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateActivityTemplateTest() throws ApiException {
        String id = null;
        TemplateResource activityTemplateResource = null;
        TemplateResource response = api.updateActivityTemplate(id, activityTemplateResource);

        // TODO: test validations
    }
    
}
