/*
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.knetikcloud.api;

import com.knetikcloud.client.ApiException;
import com.knetikcloud.model.GooglePaymentRequest;
import com.knetikcloud.model.Result;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PaymentsGoogleApi
 */
@Ignore
public class PaymentsGoogleApiTest {

    private final PaymentsGoogleApi api = new PaymentsGoogleApi();

    
    /**
     * Mark an invoice paid with Google
     *
     * Mark an invoice paid with Google. Verifies signature from Google and treats the developerPayload field inside the json payload as the id of the invoice to pay. Returns the transaction ID if successful.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void handleGooglePaymentTest() throws ApiException {
        GooglePaymentRequest request = null;
        Integer response = api.handleGooglePayment(request);

        // TODO: test validations
    }
    
}
