/*
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.knetikcloud.api;

import com.knetikcloud.client.ApiException;
import com.knetikcloud.model.PageResourceMapstringobject;
import com.knetikcloud.model.Result;
import com.knetikcloud.model.SearchReferenceMapping;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SearchApi
 */
@Ignore
public class SearchApiTest {

    private final SearchApi api = new SearchApi();

    
    /**
     * Add a new object to an index
     *
     * Mainly intended for internal use.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addSearchIndexTest() throws ApiException {
        String type = null;
        String id = null;
        Object object = null;
        api.addSearchIndex(type, id, object);

        // TODO: test validations
    }
    
    /**
     * Register reference mappings
     *
     * Add a new type mapping to connect data from one index to another, or discover an exsting one. Mainly intended for internal use.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addSearchMappingsTest() throws ApiException {
        List<SearchReferenceMapping> mappings = null;
        api.addSearchMappings(mappings);

        // TODO: test validations
    }
    
    /**
     * Delete an object
     *
     * Mainly intended for internal use. Requires SEARCH_ADMIN.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteSearchIndexTest() throws ApiException {
        String type = null;
        String id = null;
        api.deleteSearchIndex(type, id);

        // TODO: test validations
    }
    
    /**
     * Delete all objects in an index
     *
     * Mainly intended for internal use
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteSearchIndexesTest() throws ApiException {
        String type = null;
        api.deleteSearchIndexes(type);

        // TODO: test validations
    }
    
    /**
     * Search an index
     *
     * The body is an ElasticSearch query in JSON format. Please see their &lt;a href&#x3D;&#39;https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl.html&#39;&gt;documentation&lt;/a&gt; for details on the format and search options. The searchable object&#39;s format depends on on the type. See individual search endpoints on other resources for details on their format.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void searchIndexTest() throws ApiException {
        String type = null;
        Object query = null;
        Integer size = null;
        Integer page = null;
        PageResourceMapstringobject response = api.searchIndex(type, query, size, page);

        // TODO: test validations
    }
    
}
