/*
 * Knetik Platform API Documentation Latest
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://demo.sandbox.knetikcloud.com
 *
 * OpenAPI spec version: Latest
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.AchievementDefinitionResource;
import io.swagger.client.model.AchievementProgressUpdateRequest;
import io.swagger.client.model.BreTriggerResource;
import io.swagger.client.model.PageResourceAchievementDefinitionResource;
import io.swagger.client.model.PageResourceTemplateResource;
import io.swagger.client.model.PageResourceUserAchievementGroupResource;
import io.swagger.client.model.TemplateResource;
import io.swagger.client.model.UserAchievementGroupResource;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for GamificationAchievementsApi
 */
@Ignore
public class GamificationAchievementsApiTest {

    private final GamificationAchievementsApi api = new GamificationAchievementsApi();

    
    /**
     * Create a new achievement definition
     *
     * If the definition contains a trigger event name, a BRE rule is created, so that tracking logic is executed when the triggering event occurs. If no trigger event name is specified, the user&#39;s achievement status must manually be updated via the API.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createAchievementUsingPOSTTest() throws ApiException {
        AchievementDefinitionResource achievement = null;
        AchievementDefinitionResource response = api.createAchievementUsingPOST(achievement);

        // TODO: test validations
    }
    
    /**
     * Create an achievement template
     *
     * Achievement templates define a type of achievement and the properties they have
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createTemplateUsingPOSTTest() throws ApiException {
        TemplateResource template = null;
        TemplateResource response = api.createTemplateUsingPOST(template);

        // TODO: test validations
    }
    
    /**
     * Delete an achievement template
     *
     * If cascade &#x3D; &#39;detach&#39;, it will force delete the template even if it&#39;s attached to other objects
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteAchievementTemplateUsingDELETETest() throws ApiException {
        String id = null;
        String cascade = null;
        api.deleteAchievementTemplateUsingDELETE(id, cascade);

        // TODO: test validations
    }
    
    /**
     * Delete an achievement definition
     *
     * Will also disable the associated generated rule, if any.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteAchievementUsingDELETETest() throws ApiException {
        String name = null;
        api.deleteAchievementUsingDELETE(name);

        // TODO: test validations
    }
    
    /**
     * Get a list of derived achievements
     *
     * Used by other services that depend on achievements
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findAllByGroupNameUsingGETTest() throws ApiException {
        String name = null;
        List<AchievementDefinitionResource> response = api.findAllByGroupNameUsingGET(name);

        // TODO: test validations
    }
    
    /**
     * Get a single achievement template
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAchievementTemplateUsingGETTest() throws ApiException {
        String id = null;
        TemplateResource response = api.getAchievementTemplateUsingGET(id);

        // TODO: test validations
    }
    
    /**
     * List and search achievement templates
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAchievementTemplatesUsingGETTest() throws ApiException {
        Integer size = null;
        Integer page = null;
        String order = null;
        PageResourceTemplateResource response = api.getAchievementTemplatesUsingGET(size, page, order);

        // TODO: test validations
    }
    
    /**
     * Get a single achievement definition
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAchievementUsingGETTest() throws ApiException {
        String name = null;
        AchievementDefinitionResource response = api.getAchievementUsingGET(name);

        // TODO: test validations
    }
    
    /**
     * Get all achievement definitions in the system
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAchievementsUsingGETTest() throws ApiException {
        String filterTagset = null;
        String filterName = null;
        Boolean filterHidden = null;
        Boolean filterDerived = null;
        Integer size = null;
        Integer page = null;
        String order = null;
        PageResourceAchievementDefinitionResource response = api.getAchievementsUsingGET(filterTagset, filterName, filterHidden, filterDerived, size, page, order);

        // TODO: test validations
    }
    
    /**
     * Retrieve progress on a given achievement for all users
     *
     * Assets will not be filled in on the resources returned. Use &#39;Get single achievement progress for user&#39; to retrieve the full resource with assets for a given user as needed.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllUserProgressForAchievementUsingGETTest() throws ApiException {
        String achievementName = null;
        Boolean filterAchievementDerived = null;
        String filterAchievementTagset = null;
        Boolean filterAchievementHidden = null;
        Integer size = null;
        Integer page = null;
        PageResourceUserAchievementGroupResource response = api.getAllUserProgressForAchievementUsingGET(achievementName, filterAchievementDerived, filterAchievementTagset, filterAchievementHidden, size, page);

        // TODO: test validations
    }
    
    /**
     * Retrieve progress on achievements for all users
     *
     * Assets will not be filled in on the resources returned. Use &#39;Get single achievement progress for user&#39; to retrieve the full resource with assets for a given user as needed.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllUserProgressUsingGETTest() throws ApiException {
        Boolean filterAchievementDerived = null;
        String filterAchievementTagset = null;
        String filterAchievementName = null;
        Boolean filterAchievementHidden = null;
        Integer size = null;
        Integer page = null;
        PageResourceUserAchievementGroupResource response = api.getAllUserProgressUsingGET(filterAchievementDerived, filterAchievementTagset, filterAchievementName, filterAchievementHidden, size, page);

        // TODO: test validations
    }
    
    /**
     * Get the list of triggers that can be used to trigger an achievement progress update
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAvailableTriggersUsingGETTest() throws ApiException {
        List<BreTriggerResource> response = api.getAvailableTriggersUsingGET();

        // TODO: test validations
    }
    
    /**
     * Retrieve progress on a given achievement for a given user
     *
     * Assets will not be filled in on the resources returned. Use &#39;Get a single poll&#39; to retrieve the full resource with assets for a given item as needed.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUserProgressForAchievementUsingGETTest() throws ApiException {
        Integer userId = null;
        String achievementName = null;
        UserAchievementGroupResource response = api.getUserProgressForAchievementUsingGET(userId, achievementName);

        // TODO: test validations
    }
    
    /**
     * Retrieve progress on achievements for a given user
     *
     * Assets will not be filled in on the resources returned. Use &#39;Get a single poll&#39; to retrieve the full resource with assets for a given item as needed.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUserProgressUsingGETTest() throws ApiException {
        Integer userId = null;
        Boolean filterAchievementDerived = null;
        String filterAchievementTagset = null;
        String filterAchievementName = null;
        Boolean filterAchievementHidden = null;
        Integer size = null;
        Integer page = null;
        PageResourceUserAchievementGroupResource response = api.getUserProgressUsingGET(userId, filterAchievementDerived, filterAchievementTagset, filterAchievementName, filterAchievementHidden, size, page);

        // TODO: test validations
    }
    
    /**
     * Update an achievement definition
     *
     * The existing generated rule, if any, will be deleted. A new rule will be created if a trigger event name is specified in the new version.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateAchievementUsingPUTTest() throws ApiException {
        String name = null;
        AchievementDefinitionResource achievement = null;
        api.updateAchievementUsingPUT(name, achievement);

        // TODO: test validations
    }
    
    /**
     * Update or create an achievement progress record for a user
     *
     * If no progress record yet exists for the user, it will be created. Otherwise it will be updated. If progress meets or exceeds the achievement&#39;s max_value it will be marked as earned and a BRE event will be triggered for the &lt;code&gt;BreAchievementEarnedTrigger&lt;/code&gt;.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateProgressUsingPUTTest() throws ApiException {
        Integer userId = null;
        String achievementName = null;
        AchievementProgressUpdateRequest request = null;
        UserAchievementGroupResource response = api.updateProgressUsingPUT(userId, achievementName, request);

        // TODO: test validations
    }
    
    /**
     * Update an achievement template
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateTemplateUsingPUTTest() throws ApiException {
        String id = null;
        TemplateResource template = null;
        api.updateTemplateUsingPUT(id, template);

        // TODO: test validations
    }
    
}
